# Application
quarkus.application.name=quarkus-micrometer-demo
quarkus.http.port=8080

# Micrometer / Prometheus
quarkus.micrometer.enabled=true
quarkus.micrometer.registry-enabled-default=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics
quarkus.micrometer.

# Tags globais (aparecem em todas as métricas)
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true

# Health
quarkus.smallrye-health.root-path=/q/health

quarkus.container-image.builder=docker
quarkus.container-image.group=fabricio211
quarkus.container-image.name=quarkus-micrometer-demo
quarkus.container-image.tag=latest
quarkus.container-image.dockerfile-jvm-path=src/main/docker/Dockerfile.jvm


# Log
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

quarkus.langchain4j.anthropic.api-key=${OPENAI_API_KEY}

quarkus.langchain4j.anthropic.chat-model.model-name=claude-sonnet-4-5-20250929
quarkus.langchain4j.anthropic.chat-model.log-requests=true
quarkus.langchain4j.anthropic.chat-model.log-responses=true

# If you want to use a different provider or run an LLM on your local machine,
# uncomment this line and update the url/port accordingly.
#quarkus.langchain4j.openai.base-url=http://localhost:35000/v1